// AUTO-GENERATED by scripts/import-country-snapshots.ts. Do not edit by hand.
import type { Catalogue } from "./catalogue";

export const catalogue: Catalogue = {
  "generatedAt": "2026-06-08T00:00:00Z",
  "sourceFile": "country_snapshots_2025.xlsx",
  "countries": [
    {
      "code": "AS",
      "name": "American Samoa",
      "region": "POL",
      "mfatRelevant": false
    },
    {
      "code": "CK",
      "name": "Cook Islands",
      "region": "POL",
      "mfatRelevant": true
    },
    {
      "code": "FJ",
      "name": "Fiji",
      "region": "MEL",
      "mfatRelevant": true
    },
    {
      "code": "FM",
      "name": "Micronesia (Federated States of)",
      "region": "MIC",
      "mfatRelevant": true
    },
    {
      "code": "GU",
      "name": "Guam",
      "region": "MIC",
      "mfatRelevant": false
    },
    {
      "code": "KI",
      "name": "Kiribati",
      "region": "MIC",
      "mfatRelevant": true
    },
    {
      "code": "MH",
      "name": "Marshall Islands",
      "region": "MIC",
      "mfatRelevant": true
    },
    {
      "code": "MP",
      "name": "Northern Mariana Islands",
      "region": "MIC",
      "mfatRelevant": false
    },
    {
      "code": "NC",
      "name": "New Caledonia",
      "region": "MEL",
      "mfatRelevant": false
    },
    {
      "code": "NR",
      "name": "Nauru",
      "region": "MIC",
      "mfatRelevant": true
    },
    {
      "code": "NU",
      "name": "Niue",
      "region": "POL",
      "mfatRelevant": true
    },
    {
      "code": "PF",
      "name": "French Polynesia",
      "region": "POL",
      "mfatRelevant": false
    },
    {
      "code": "PG",
      "name": "Papua New Guinea",
      "region": "MEL",
      "mfatRelevant": true
    },
    {
      "code": "PN",
      "name": "Pitcairn",
      "region": "POL",
      "mfatRelevant": false
    },
    {
      "code": "PW",
      "name": "Palau",
      "region": "MIC",
      "mfatRelevant": true
    },
    {
      "code": "SB",
      "name": "Solomon Islands",
      "region": "MEL",
      "mfatRelevant": true
    },
    {
      "code": "TK",
      "name": "Tokelau",
      "region": "POL",
      "mfatRelevant": true
    },
    {
      "code": "TO",
      "name": "Tonga",
      "region": "POL",
      "mfatRelevant": true
    },
    {
      "code": "TV",
      "name": "Tuvalu",
      "region": "POL",
      "mfatRelevant": true
    },
    {
      "code": "VU",
      "name": "Vanuatu",
      "region": "MEL",
      "mfatRelevant": true
    },
    {
      "code": "WF",
      "name": "Wallis and Futuna",
      "region": "POL",
      "mfatRelevant": false
    },
    {
      "code": "WS",
      "name": "Samoa",
      "region": "POL",
      "mfatRelevant": true
    }
  ],
  "themes": [
    {
      "id": "I",
      "slug": "context",
      "title": "Context",
      "order": 1
    },
    {
      "id": "II",
      "slug": "health",
      "title": "Health",
      "order": 2
    },
    {
      "id": "III",
      "slug": "education",
      "title": "Education",
      "order": 3
    },
    {
      "id": "IV",
      "slug": "economic-resilience",
      "title": "Economic resilience",
      "order": 4
    },
    {
      "id": "V",
      "slug": "industry-and-innovation",
      "title": "Industry & Innovation",
      "order": 5
    },
    {
      "id": "VI",
      "slug": "infrastructure-and-energy",
      "title": "Infrastructure & energy",
      "order": 6
    },
    {
      "id": "VII",
      "slug": "climate-and-environment",
      "title": "Climate & environment",
      "order": 7
    },
    {
      "id": "VIII",
      "slug": "oceans-and-fisheries",
      "title": "Oceans & fisheries",
      "order": 8
    },
    {
      "id": "IX",
      "slug": "governance-and-institutions",
      "title": "Governance & Institutions",
      "order": 9
    },
    {
      "id": "X",
      "slug": "peace-and-security",
      "title": "Peace & security",
      "order": 10
    },
    {
      "id": "XI",
      "slug": "social-inclusion",
      "title": "Social inclusion",
      "order": 11
    },
    {
      "id": "XII",
      "slug": "official-development-assistance",
      "title": "Official Development Assistance",
      "order": 12
    }
  ],
  "indicators": [
    {
      "id": "I.1",
      "themeId": "I",
      "title": "Constitutional form",
      "rendering": "TABLE",
      "dataflow": "DF_KEYFACTS",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_KEYFACTS,/A.[TAG_GEO].GOV?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?fs[0]=Topic%2C0%7CMulti-domain%23XDO%23&pg=0&fc=Topic&bp=true&snb=6&df[ds]=ds%3ASPC2&df[id]=DF_KEYFACTS&df[ag]=SPC&df[vs]=1.0&pd=2020%2C2021&dq=A..GOV&ly[rw]=GEO_PICT",
      "notes": "New"
    },
    {
      "id": "I.2",
      "themeId": "I",
      "title": "Head of State",
      "rendering": "TABLE"
    },
    {
      "id": "I.3",
      "themeId": "I",
      "title": "Basis of Executive Legitimacy",
      "rendering": "TABLE"
    },
    {
      "id": "I.5",
      "themeId": "I",
      "title": "Mid-year population estimate",
      "rendering": "TABLE",
      "dataflow": "DF_POP_PROJ",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_POP_PROJ,/A.[TAG_GEO].MIDYEARPOPEST._T._T?startPeriod=2015&endPeriod=2025&dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&df[ds]=ds%3ASPC2&df[id]=DF_POP_PROJ&df[ag]=SPC&df[vs]=3.0&dq=A.[TAG_GEO].MIDYEARPOPEST._T._T&pd=%2C&ly[rw]=TIME_PERIOD"
    },
    {
      "id": "I.6",
      "themeId": "I",
      "title": "Urban population (%)",
      "rendering": "TABLE",
      "dataflow": "DF_POP_URBAN",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_POP_URBAN,/A.[TAG_GEO].POPRFCOU.U?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&df[ds]=ds%3ASPC2&df[id]=DF_POP_URBAN&df[ag]=SPC&df[vs]=1.0&dq=A.[TAG_GEO].POPRFCOU.U&pd=%2C&ly[rw]=TIME_PERIOD"
    },
    {
      "id": "I.7",
      "themeId": "I",
      "title": "Population Median Age (Years)",
      "rendering": "TABLE",
      "dataflow": "DF_POP_AGE",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_POP_AGE,/A.[TAG_GEO].MEDIANAGE._T?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&df[ds]=ds%3ASPC2&df[id]=DF_POP_AGE&df[ag]=SPC&df[vs]=1.0&dq=A.[TAG_GEO].MEDIANAGE._T&pd=%2C&ly[rw]=TIME_PERIOD"
    },
    {
      "id": "I.8",
      "themeId": "I",
      "title": "Population growth rate over 1 year",
      "rendering": "TABLE",
      "dataflow": "DF_POP_PROJ",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_POP_PROJ,/A.[TAG_GEO].POPYGR._T._T?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&df[ds]=ds%3ASPC2&df[id]=DF_POP_PROJ&df[ag]=SPC&df[vs]=3.0&dq=A.[TAG_GEO].POPYGR._T._T&pd=%2C&ly[rw]=TIME_PERIOD"
    },
    {
      "id": "I.9",
      "themeId": "I",
      "title": "Average household size",
      "rendering": "TABLE",
      "dataflow": "DF_HHCOUNTS",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_HHCOUNTS,/A.[TAG_GEO].HHSZ?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&df[ds]=ds%3ASPC2&df[id]=DF_HHCOUNTS&df[ag]=SPC&df[vs]=1.0&dq=A.[TAG_GEO].HHSZ&pd=%2C&ly[rw]=TIME_PERIOD"
    },
    {
      "id": "I.10",
      "themeId": "I",
      "title": "Population density (km2)",
      "rendering": "TABLE",
      "dataflow": "DF_POP_DENSITY",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_POP_DENSITY,/A.[TAG_GEO].POPDENSITY?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&df[ds]=ds%3ASPC2&df[id]=DF_POP_DENSITY&df[ag]=SPC&df[vs]=1.0&dq=A.[TAG_GEO].POPDENSITY&pd=%2C&ly[rw]=TIME_PERIOD"
    },
    {
      "id": "I.11",
      "themeId": "I",
      "title": "Dependency ratio (15-64)",
      "mfatName": "Dependency ratio",
      "rendering": "TABLE",
      "dataflow": "DF_POP_AGE",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_POP_AGE,/A.[TAG_GEO].DEPRATIO1564._T?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&df[ds]=ds%3ASPC2&df[id]=DF_POP_AGE&df[ag]=SPC&df[vs]=1.0&dq=A.[TAG_GEO].DEPRATIO1564._T&pd=%2C&ly[rw]=TIME_PERIOD"
    },
    {
      "id": "I.12",
      "themeId": "I",
      "title": "Proportion of youth (15-24)",
      "mfatName": "Age dependency ratio, young (% of working-age population)",
      "rendering": "TABLE",
      "dataflow": "DF_POP_AGE",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_POP_AGE,/A.[TAG_GEO].POPYOUTH._T?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=population&pg=0&hc[Topic]=Population&snb=42&df[ds]=ds%3ASPC2&df[id]=DF_POP_AGE&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A..POPYOUTH._T&ly[rw]=GEO_PICT&to[TIME_PERIOD]=false",
      "notes": "New 2024"
    },
    {
      "id": "I.13",
      "themeId": "I",
      "title": "% of population that lives within 1km of the coast",
      "rendering": "TABLE",
      "dataflow": "DF_POP_COAST",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_POP_COAST,/A.[TAG_GEO].COASTALPOPRF.1KM?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&df[ds]=ds%3ASPC2&df[id]=DF_POP_COAST&df[ag]=SPC&df[vs]=2.0&dq=A.[TAG_GEO].COASTALPOPRF.1KM&pd=%2C&ly[rw]=TIME_PERIOD"
    },
    {
      "id": "I.14",
      "themeId": "I",
      "title": "% of population that lives within 5km of the coast",
      "rendering": "TABLE",
      "dataflow": "DF_POP_COAST",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_POP_COAST,/A.[TAG_GEO].COASTALPOPRF.5KM?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&df[ds]=ds%3ASPC2&df[id]=DF_POP_COAST&df[ag]=SPC&df[vs]=2.0&dq=A.[TAG_GEO].COASTALPOPRF.5KM&pd=%2C&ly[rw]=TIME_PERIOD"
    },
    {
      "id": "I.15",
      "themeId": "I",
      "title": "% of population that lives within 10km of the coast",
      "rendering": "TABLE",
      "dataflow": "DF_POP_COAST",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_POP_COAST,/A.[TAG_GEO].COASTALPOPRF.10KM?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&df[ds]=ds%3ASPC2&df[id]=DF_POP_COAST&df[ag]=SPC&df[vs]=2.0&dq=A.[TAG_GEO].COASTALPOPRF.10KM&pd=%2C&ly[rw]=TIME_PERIOD"
    },
    {
      "id": "I.16",
      "themeId": "I",
      "title": "Land area (km2)",
      "rendering": "TABLE",
      "dataflow": "DF_POP_DENSITY",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_POP_DENSITY,/A.[TAG_GEO].LANDAREA?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&df[ds]=ds%3ASPC2&df[id]=DF_POP_DENSITY&df[ag]=SPC&df[vs]=1.0&dq=A.[TAG_GEO].LANDAREA&pd=%2C&ly[rw]=TIME_PERIOD"
    },
    {
      "id": "I.17",
      "themeId": "I",
      "title": "Forest Area (%)",
      "rendering": "TABLE",
      "dataflow": "DF_WBWDI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_WBWDI,/A.[TAG_GEO].AG_LND_FRST_ZS?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&df[ds]=ds%3ASPC2&df[id]=DF_WBWDI&df[ag]=SPC&df[vs]=1.0&dq=A.[TAG_GEO].AG_LND_FRST_ZS&pd=%2C&ly[rw]=TIME_PERIOD",
      "notes": "Relaunch land use"
    },
    {
      "id": "I.18",
      "themeId": "I",
      "title": "Agricultural Land (%)",
      "rendering": "TABLE",
      "dataflow": "DF_WBWDI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_WBWDI,/A.[TAG_GEO].AG_LND_AGRI_ZS?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&df[ds]=ds%3ASPC2&df[id]=DF_WBWDI&df[ag]=SPC&df[vs]=1.0&dq=A.[TAG_GEO].AG_LND_AGRI_ZS&pd=%2C&ly[rw]=TIME_PERIOD",
      "notes": "Relaunch land use"
    },
    {
      "id": "I.19",
      "themeId": "I",
      "title": "Environmental Sustainability",
      "rendering": "TEXT"
    },
    {
      "id": "I.20",
      "themeId": "I",
      "title": "Ethnic fractionalisation",
      "rendering": "TEXT"
    },
    {
      "id": "I.21",
      "themeId": "I",
      "title": "Language fractionalisation",
      "rendering": "TEXT"
    },
    {
      "id": "I.22",
      "themeId": "I",
      "title": "Religion fractionalisation",
      "rendering": "TEXT"
    },
    {
      "id": "II.1",
      "themeId": "II",
      "title": "Life expectancy at birth (male)",
      "mfatName": "Life expectancy at birth, by sex",
      "rendering": "CHART",
      "dataflow": "DF_VITAL",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_VITAL,/A.[TAG_GEO].LEB.M?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=expectancy&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_VITAL&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].LEB.M&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "II.2",
      "themeId": "II",
      "title": "Life expectancy at birth (female)",
      "mfatName": "Life expectancy at birth, by sex",
      "rendering": "CHART",
      "dataflow": "DF_VITAL",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_VITAL,/A.[TAG_GEO].LEB.F?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=expectancy&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_VITAL&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].LEB.F&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "II.3",
      "themeId": "II",
      "title": "Total fertility rate",
      "rendering": "CHART",
      "dataflow": "DF_VITAL",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_VITAL,/A.[TAG_GEO].TFR.?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=fertility&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_VITAL&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].TFR.&ly[cl]=TIME_PERIOD",
      "notes": "Was DF_POKCET"
    },
    {
      "id": "II.9",
      "themeId": "II",
      "title": "Contraceptive prevalence rate (%)",
      "mfatName": "Modern contraceptive prevalence rate",
      "rendering": "CHART",
      "dataflow": "DF_NMDI_HEA",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI_HEA,/A.[TAG_GEO].NMDI0116.._T._T..?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=contraceptive&pg=0&snb=6&df[ds]=ds%3ASPC2&df[id]=DF_NMDI_HEA&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A..NMDI0116._T._T._T..&ly[rw]=GEO_PICT&ly[cl]=TIME_PERIOD",
      "notes": "New"
    },
    {
      "id": "II.11",
      "themeId": "II",
      "title": "Proportion of 1 year old children immunized against measles (%)",
      "mfatName": "Immunisation coverage by vaccine (three main types - DPT, HepB3, Measles)",
      "rendering": "CHART",
      "dataflow": "DF_NMDI_HEA",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI_HEA,/A.[TAG_GEO].NMDI0103._T._T._T..?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?fs[0]=Development%20indicators%2C0%7CNational%20Minimum%20Development%20Indicators%23NMDI%23&pg=0&fc=Development%20indicators&bp=true&snb=8&df[ds]=ds%3ASPC2&df[id]=DF_NMDI_HEA&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A..NMDI0103._T._T._T..&ly[rw]=GEO_PICT&ly[cl]=TIME_PERIOD&to[TIME_PERIOD]=false",
      "notes": "New 2024"
    },
    {
      "id": "II.12",
      "themeId": "II",
      "title": "Proportion of one year olds fully immunized against EPI target diseases (3 doses diptheria, tetanus, toxoid & pertussis) (%)",
      "mfatName": "Immunisation coverage by vaccine (three main types - DPT, HepB3, Measles)",
      "rendering": "CHART",
      "dataflow": "DF_NMDI_HEA",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI_HEA,/A.[TAG_GEO].NMDI0145._T._T._T..?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?fs[0]=Development%20indicators%2C0%7CNational%20Minimum%20Development%20Indicators%23NMDI%23&pg=0&fc=Development%20indicators&bp=true&snb=8&df[ds]=ds%3ASPC2&df[id]=DF_NMDI_HEA&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A..NMDI0145._T._T._T..&ly[rw]=GEO_PICT&ly[cl]=TIME_PERIOD&to[TIME_PERIOD]=false",
      "notes": "New 2024"
    },
    {
      "id": "II.13",
      "themeId": "II",
      "title": "Proportion of one year olds fully immunized against EPI target diseases (3 doses hepatitis B - HepB3) (%)",
      "mfatName": "Immunisation coverage by vaccine (three main types - DPT, HepB3, Measles)",
      "rendering": "CHART",
      "dataflow": "DF_NMDI_HEA",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI_HEA,/A.[TAG_GEO].NMDI0146._T._T._T..?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?fs[0]=Development%20indicators%2C0%7CNational%20Minimum%20Development%20Indicators%23NMDI%23&pg=0&fc=Development%20indicators&bp=true&snb=8&df[ds]=ds%3ASPC2&df[id]=DF_NMDI_HEA&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A..NMDI0146._T._T._T..&ly[rw]=GEO_PICT&ly[cl]=TIME_PERIOD&to[TIME_PERIOD]=false",
      "notes": "New 2024"
    },
    {
      "id": "II.14",
      "themeId": "II",
      "title": "Mortality rate attributed to cardiovascular disease, cancer, chronic respiratory disease or diabetes",
      "rendering": "CHART",
      "dataflow": "DF_NMDI_HEA",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI_HEA,/A.[TAG_GEO].SH_DTH_NCD._T._T._T..?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&tm=mortality%20rate&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_NMDI_HEA&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].SH_DTH_NCD._T._T._T..&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "II.15",
      "themeId": "II",
      "title": "Prevalence of overweight or obese adults - BMI >= 25.0",
      "mfatName": "Prevalence of obesity among adults (%)",
      "rendering": "CHART",
      "dataflow": "DF_NMDI_HEA",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI_HEA,/A.[TAG_GEO].NMDI0131._T._T._T..?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=health&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_NMDI_HEA&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].NMDI0131._T._T._T.."
    },
    {
      "id": "II.23",
      "themeId": "II",
      "title": "-",
      "mfatName": "NCD - Health system response programmes (six sub-components)",
      "rendering": "TEXT"
    },
    {
      "id": "III.1",
      "themeId": "III",
      "title": "Education drop-out rates (%)",
      "mfatName": "Education drop-out rates (%) (by sex and school year",
      "rendering": "CHART",
      "dataflow": "DF_NMDI_EDU",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI_EDU,/A.[TAG_GEO].NMDI0429._T._T._T..?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&df[ds]=ds%3ASPC2&df[id]=DF_NMDI_EDU&df[ag]=SPC&df[vs]=1.0&dq=A.[TAG_GEO].NMDI0429._T._T._T..&pd=%2C&tm=education&pg=0&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "III.2",
      "themeId": "III",
      "title": "Government expenditure on education as % of total government expenditure",
      "rendering": "CHART",
      "dataflow": "DF_NMDI_EDU",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI_EDU,/A.[TAG_GEO].NMDI0020._T._T._T..?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=education&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_NMDI_EDU&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].NMDI0020._T._T._T.."
    },
    {
      "id": "III.5",
      "themeId": "III",
      "title": "Transition rate (primary/secondary)",
      "mfatName": "Survival rate to the last grade of lower secondary general education (%) (Transition rate)",
      "rendering": "CHART",
      "dataflow": "DF_NMDI_EDU",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI_EDU,/A.[TAG_GEO].NMDI0431._T._T._T..?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=transition%20rate&pg=0&snb=2&df[ds]=ds%3ASPC2&df[id]=DF_NMDI_EDU&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A..NMDI0431._T._T._T..&ly[rw]=GEO_PICT&ly[cl]=TIME_PERIOD&to[TIME_PERIOD]=false",
      "notes": "New 2024"
    },
    {
      "id": "III.6",
      "themeId": "III",
      "title": "Educational attainment",
      "mfatName": "Percentage of population (age 25 and over) by highest level of educational attainment (primary and lower secondary), by sex",
      "rendering": "CHART",
      "notes": "New 2024 | Update with the gender data"
    },
    {
      "id": "III.7",
      "themeId": "III",
      "title": "Literacy Rates of 15-24 year olds (%)",
      "mfatName": "Literacy rate of youth (%ages 15-24) - by sex and rural/urban",
      "rendering": "CHART",
      "dataflow": "DF_NMDI_EDU",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI_EDU,/A.[TAG_GEO].NMDI0019._T._T._T..?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=literacy%20rate&pg=0&snb=5&df[ds]=ds%3ASPC2&df[id]=DF_NMDI_EDU&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A..NMDI0019._T._T._T..&ly[rw]=GEO_PICT&ly[cl]=TIME_PERIOD",
      "notes": "New"
    },
    {
      "id": "III.8",
      "themeId": "III",
      "title": "Literacy Rates of 15-24 year olds (% - female)",
      "mfatName": "Literacy rate of youth (%ages 15-24) - by sex and rural/urban",
      "rendering": "CHART",
      "dataflow": "DF_NMDI_EDU",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI_EDU,/A.[TAG_GEO].NMDI0019.F._T._T..?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=literacy%20rate&pg=0&snb=5&df[ds]=ds%3ASPC2&df[id]=DF_NMDI_EDU&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A..NMDI0019.F._T._T..&ly[rw]=GEO_PICT&ly[cl]=TIME_PERIOD&to[TIME_PERIOD]=false",
      "notes": "New 2024"
    },
    {
      "id": "III.9",
      "themeId": "III",
      "title": "Literacy Rates of 15-24 year olds (% - male)",
      "mfatName": "Literacy rate of youth (%ages 15-24) - by sex and rural/urban",
      "rendering": "CHART",
      "dataflow": "DF_NMDI_EDU",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI_EDU,/A.[TAG_GEO].NMDI0019.M._T._T..?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=literacy%20rate&pg=0&snb=5&df[ds]=ds%3ASPC2&df[id]=DF_NMDI_EDU&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A..NMDI0019.M._T._T..&ly[rw]=GEO_PICT&ly[cl]=TIME_PERIOD&to[TIME_PERIOD]=false&lb=nm",
      "notes": "New 2024"
    },
    {
      "id": "III.10",
      "themeId": "III",
      "title": "Literacy Rates of 15-24 year olds (% - urban)",
      "mfatName": "Literacy rate of youth (%ages 15-24) - by sex and rural/urban",
      "rendering": "CHART",
      "dataflow": "DF_NMDI_EDU",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI_EDU,/A.[TAG_GEO].NMDI0019._T._T.U._T.?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?fs[0]=Development%20indicators%2C0%7CNational%20Minimum%20Development%20Indicators%23NMDI%23&pg=0&fc=Development%20indicators&bp=true&snb=8&df[ds]=ds%3ASPC2&df[id]=DF_NMDI_EDU&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A..NMDI0019._T._T.U._T.&ly[rw]=GEO_PICT&ly[cl]=TIME_PERIOD&to[TIME_PERIOD]=false",
      "notes": "New 2024"
    },
    {
      "id": "III.11",
      "themeId": "III",
      "title": "Literacy Rates of 15-24 year olds (% - rural)",
      "mfatName": "Literacy rate of youth (%ages 15-24) - by sex and rural/urban",
      "rendering": "CHART",
      "dataflow": "DF_NMDI_EDU",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI_EDU,/A.[TAG_GEO].NMDI0019._T._T.R._T.?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?fs[0]=Development%20indicators%2C0%7CNational%20Minimum%20Development%20Indicators%23NMDI%23&pg=0&fc=Development%20indicators&bp=true&snb=8&df[ds]=ds%3ASPC2&df[id]=DF_NMDI_EDU&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A..NMDI0019._T._T.R._T.&ly[rw]=GEO_PICT&ly[cl]=TIME_PERIOD&to[TIME_PERIOD]=false",
      "notes": "New 2024"
    },
    {
      "id": "III.12",
      "themeId": "III",
      "title": "Literacy Rates of 25-64 year olds (%)",
      "mfatName": "Literacy rate of adults (%ages 25-64) - by sex and rural/urban",
      "rendering": "CHART",
      "dataflow": "DF_UIS",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_UIS,/A.[TAG_GEO].LR_AG25T64?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=literacy%20rate&pg=0&snb=5&df[ds]=ds%3ASPC2&df[id]=DF_UIS&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A..LR_AG25T64&ly[rw]=INDICATOR&ly[cl]=TIME_PERIOD&to[TIME_PERIOD]=false",
      "notes": "New 2024"
    },
    {
      "id": "III.13",
      "themeId": "III",
      "title": "Literacy Rates of 25-64 year olds (% - female)",
      "mfatName": "Literacy rate of adults (%ages 25-64) - by sex and rural/urban",
      "rendering": "CHART",
      "dataflow": "DF_UIS",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_UIS,/A.[TAG_GEO].LR_AG25T64_F?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=literacy%20rate&pg=0&snb=5&df[ds]=ds%3ASPC2&df[id]=DF_UIS&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A..LR_AG25T64_F&ly[rw]=INDICATOR&ly[cl]=TIME_PERIOD&to[TIME_PERIOD]=false",
      "notes": "New 2024"
    },
    {
      "id": "III.14",
      "themeId": "III",
      "title": "Literacy Rates of 25-64 year olds (% - male)",
      "mfatName": "Literacy rate of adults (%ages 25-64) - by sex and rural/urban",
      "rendering": "CHART",
      "dataflow": "DF_UIS",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_UIS,/A.[TAG_GEO].LR_AG25T64_M?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=literacy%20rate&pg=0&snb=5&df[ds]=ds%3ASPC2&df[id]=DF_UIS&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A..LR_AG25T64_M&ly[rw]=INDICATOR&ly[cl]=TIME_PERIOD&to[TIME_PERIOD]=false",
      "notes": "New 2024"
    },
    {
      "id": "III.21",
      "themeId": "III",
      "title": "-",
      "mfatName": "Compulsory school ages and ranges for primary and secondary",
      "rendering": "TEXT"
    },
    {
      "id": "III.22",
      "themeId": "III",
      "title": "-",
      "mfatName": "Government scholarships: ratio women to men",
      "rendering": "TEXT"
    },
    {
      "id": "III.23",
      "themeId": "III",
      "title": "-",
      "mfatName": "Mean years of schooling",
      "rendering": "TEXT"
    },
    {
      "id": "III.24",
      "themeId": "III",
      "title": "-",
      "mfatName": "Expected years of schooling",
      "rendering": "TEXT"
    },
    {
      "id": "IV.1",
      "themeId": "IV",
      "title": "Annual GDP growth (%)",
      "rendering": "CHART",
      "dataflow": "DF_NATIONAL_ACCOUNTS",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NATIONAL_ACCOUNTS,/A.USD.[TAG_GEO].GDPCVR?endPeriod=2021&dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?fs[0]=Topic%2C0%7CEconomy%23ECO%23&pg=0&fc=Topic&df[ds]=ds%3ASPC2&df[id]=DF_NATIONAL_ACCOUNTS&df[ag]=SPC&df[vs]=1.0&pd=%2C2021&dq=A.USD.[TAG_GEO].GDPCVR&ly[cl]=TIME_PERIOD",
      "notes": "Was DF_WBWDI"
    },
    {
      "id": "IV.2",
      "themeId": "IV",
      "title": "Overall Fiscal Balance of Central Government (surplus/deficit) % of GDP",
      "mfatName": "Fiscal balance of central government (% of GDP)",
      "rendering": "CHART",
      "dataflow": "DF_SOCECO",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_SOCECO,/A.[TAG_GEO].OFB2GDP?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=covid%2019&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_SOCECO&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].OFB2GDP&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "IV.3",
      "themeId": "IV",
      "title": "Agriculture, value added (% of GDP)",
      "mfatName": "Agriculture, Industry and Services (% of GDP)",
      "rendering": "CHART",
      "dataflow": "DF_WBWDI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_WBWDI,/A.[TAG_GEO].NV_AGR_TOTL_ZS?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=wb%20wdi&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_WBWDI&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].NV_AGR_TOTL_ZS&ly[cl]=TIME_PERIOD",
      "notes": "Relaunch GDP"
    },
    {
      "id": "IV.4",
      "themeId": "IV",
      "title": "Industry, value added (% of GDP)",
      "mfatName": "Agriculture, Industry and Services (% of GDP)",
      "rendering": "CHART",
      "dataflow": "DF_WBWDI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_WBWDI,/A.[TAG_GEO].NV_IND_TOTL_ZS?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=wb%20wdi&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_WBWDI&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].NV_IND_TOTL_ZS&ly[cl]=TIME_PERIOD",
      "notes": "Relaunch GDP"
    },
    {
      "id": "IV.5",
      "themeId": "IV",
      "title": "Services (% of GDP)",
      "mfatName": "Agriculture, Industry and Services (% of GDP)",
      "rendering": "CHART",
      "dataflow": "DF_WBWDI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_WBWDI,/A.[TAG_GEO].NV_SRV_TOTL_ZS?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=wb%20wdi&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_WBWDI&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].NV_SRV_TOTL_ZS&ly[cl]=TIME_PERIOD",
      "notes": "Relaunch GDP"
    },
    {
      "id": "IV.9",
      "themeId": "IV",
      "title": "GINI index (World Bank estimate)",
      "rendering": "CHART",
      "dataflow": "DF_WBWDI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_WBWDI,/A.[TAG_GEO].SI_POV_GINI?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=wb%20wdi&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_WBWDI&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].SI_POV_GINI&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "IV.11",
      "themeId": "IV",
      "title": "GDP, per capita, in USD",
      "mfatName": "GDP, per capita, (US$)",
      "rendering": "CHART",
      "dataflow": "DF_NATIONAL_ACCOUNTS",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NATIONAL_ACCOUNTS,/A.USD.[TAG_GEO].GDPCPC?endPeriod=2021&dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?fs[0]=Topic%2C0%7CEconomy%23ECO%23&pg=0&fc=Topic&df[ds]=ds%3ASPC2&df[id]=DF_NATIONAL_ACCOUNTS&df[ag]=SPC&df[vs]=1.0&pd=%2C2021&dq=A.USD.[TAG_GEO].GDPCPC&ly[cl]=TIME_PERIOD",
      "notes": "Was DF_POCKET"
    },
    {
      "id": "IV.12",
      "themeId": "IV",
      "title": "Age dependency ratio, young (% of working-age population)",
      "rendering": "TEXT"
    },
    {
      "id": "IX.1",
      "themeId": "IX",
      "title": "Voice and Accountability",
      "rendering": "CHART",
      "dataflow": "DF_WBWGI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_WBWGI,/A.[TAG_GEO].VA_EST?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=voice%20and%20accountability&pg=0&hc[Indicator]=Voice%20and%20Accountability&df[ds]=ds%3ASPC2&df[id]=DF_WBWGI&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].VA_EST&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "IX.2",
      "themeId": "IX",
      "title": "Rule of Law",
      "rendering": "CHART",
      "dataflow": "DF_WBWGI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_WBWGI,/A.[TAG_GEO].RL_EST?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=voice%20and%20accountability&pg=0&hc[Indicator]=Voice%20and%20Accountability&df[ds]=ds%3ASPC2&df[id]=DF_WBWGI&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].RL_EST&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "IX.3",
      "themeId": "IX",
      "title": "Government Effectiveness",
      "rendering": "CHART",
      "dataflow": "DF_WBWGI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_WBWGI,/A.[TAG_GEO].GE_EST?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=voice%20and%20accountability&pg=0&hc[Indicator]=Voice%20and%20Accountability&df[ds]=ds%3ASPC2&df[id]=DF_WBWGI&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].GE_EST&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "IX.4",
      "themeId": "IX",
      "title": "Control of Corruption",
      "rendering": "CHART",
      "dataflow": "DF_WBWGI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_WBWGI,/A.[TAG_GEO].CC_EST?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=voice%20and%20accountability&pg=0&hc[Indicator]=Voice%20and%20Accountability&df[ds]=ds%3ASPC2&df[id]=DF_WBWGI&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].CC_EST&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "IX.5",
      "themeId": "IX",
      "title": "Regulatory quality",
      "rendering": "CHART",
      "dataflow": "DF_WBWGI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_WBWGI,/A.[TAG_GEO].RQ_EST?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=voice%20and%20accountability&pg=0&hc[Indicator]=Voice%20and%20Accountability&df[ds]=ds%3ASPC2&df[id]=DF_WBWGI&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].RQ_EST&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "IX.6",
      "themeId": "IX",
      "title": "Political Stability and Absence of Violence/Terrorism",
      "rendering": "CHART",
      "dataflow": "DF_WBWGI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_WBWGI,/A.[TAG_GEO].PV_EST?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=voice%20and%20accountability&pg=0&hc[Indicator]=Voice%20and%20Accountability&df[ds]=ds%3ASPC2&df[id]=DF_WBWGI&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].PV_EST&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "IX.7",
      "themeId": "IX",
      "title": "Number of persons in prison",
      "mfatName": "Persons held in prison (rate per 100,000)",
      "rendering": "CHART",
      "dataflow": "DF_PRISON",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_PRISON,/A.[TAG_GEO].COUNT?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=prison&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_PRISON&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].COUNT&ly[rw]=TIME_PERIOD"
    },
    {
      "id": "IX.11",
      "themeId": "IX",
      "title": "-",
      "mfatName": "PEFA Assessment",
      "rendering": "TEXT"
    },
    {
      "id": "IX.12",
      "themeId": "IX",
      "title": "-",
      "mfatName": "Improvement against 50% or more of SDGs",
      "rendering": "TEXT"
    },
    {
      "id": "V.1",
      "themeId": "V",
      "title": "E-Government Index",
      "mfatName": "UN E-Government Index",
      "rendering": "CHART",
      "dataflow": "DF_EGOV",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_EGOV,/A.[TAG_GEO].EGI?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=government&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_EGOV&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].EGI&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "V.2",
      "themeId": "V",
      "title": "Gross tourism earnings as percentage of GDP",
      "mfatName": "Gross tourism earnings as % of GDP",
      "rendering": "CHART",
      "dataflow": "DF_TOURISM_EARNINGS",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_TOURISM_EARNINGS,/A.[TAG_GEO].EARN2GDP.USD?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=tourism&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_TOURISM_EARNINGS&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].EARN2GDP.USD&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "V.3",
      "themeId": "V",
      "title": "Gross tourism earnings per visitor (US$)",
      "mfatName": "Tourism receipts per arrival",
      "rendering": "CHART",
      "dataflow": "DF_TOURISM_EARNINGS",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_TOURISM_EARNINGS,/A.[TAG_GEO].EARN2VIS.USD?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=tourism&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_TOURISM_EARNINGS&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].EARN2VIS.USD&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "V.4",
      "themeId": "V",
      "title": "Number of overseas visitors arrivals",
      "mfatName": "Tourism numbers of arrivals",
      "rendering": "CHART",
      "dataflow": "DF_OVERSEAS_VISITORS",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_OVERSEAS_VISITORS,/A.[TAG_GEO]._T.NOSVA?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=visitor&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_OVERSEAS_VISITORS&df[ag]=SPC&df[vs]=2.0&pd=%2C&dq=A.[TAG_GEO]._T.NOSVA&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "V.5",
      "themeId": "V",
      "title": "Digital Adoption Index",
      "rendering": "CHART",
      "dataflow": "DF_WBDAI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_WBDAI,/A.[TAG_GEO].DAI?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=wb%20dai&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_WBDAI&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].DAI&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "V.6",
      "themeId": "V",
      "title": "Individuals using the Internet, total (%)",
      "mfatName": "Proportion of individuals using the Internet",
      "rendering": "CHART",
      "dataflow": "DF_DIGITAL_DEVELOPMENT",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_DIGITAL_DEVELOPMENT,/A.[TAG_GEO].DD024?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=digital&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_DIGITAL_DEVELOPMENT&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].DD024&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "V.8",
      "themeId": "V",
      "title": "Proportion of household income from agriculture and forestry activities (%)",
      "rendering": "CHART",
      "dataflow": "DF_NMDI_FIS",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI_FIS,/A.[TAG_GEO].NMDI0057._T._T._T..?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=nmdi&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_NMDI_FIS&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].NMDI0057._T._T._T.."
    },
    {
      "id": "V.9",
      "themeId": "V",
      "title": "Proportion of labour force engaged in agriculture and forestry activities as their main economic activity (%)",
      "rendering": "CHART",
      "dataflow": "DF_NMDI_FIS",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI_FIS,/A.[TAG_GEO].NMDI0059._T._T._T..?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=nmdi&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_NMDI_FIS&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].NMDI0059._T._T._T.."
    },
    {
      "id": "VI.4",
      "themeId": "VI",
      "title": "Renewable electricity output (% of total electricity output)",
      "rendering": "CHART",
      "dataflow": "DF_WBWDI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_WBWDI,/A.[TAG_GEO].EG_ELC_RNEW_ZS?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=renewable&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_WBWDI&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].EG_ELC_RNEW_ZS&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "VI.5",
      "themeId": "VI",
      "title": "Proportion of Households with access to improved sanitation (%)",
      "mfatName": "Access to improved sanitation (% of population) by location",
      "rendering": "CHART",
      "dataflow": "DF_NMDI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI,/A.[TAG_GEO].NMDI0134._T._T._T..?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=access%20sanitation&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_NMDI&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].NMDI0134._T._T._T.."
    },
    {
      "id": "VI.6",
      "themeId": "VI",
      "title": "Proportion of Households with access to improved drinking water (%)",
      "mfatName": "Access to improved drinking water (% of population)",
      "rendering": "CHART",
      "dataflow": "DF_NMDI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_NMDI,/A.[TAG_GEO].NMDI0133._T._T._T..?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=access%20sanitation&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_NMDI&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].NMDI0133._T._T._T.."
    },
    {
      "id": "VII.1",
      "themeId": "VII",
      "title": "Global Climate Risk Index",
      "rendering": "TEXT"
    },
    {
      "id": "VII.2",
      "themeId": "VII",
      "title": "CO2 emissions, per capita (metric tons)",
      "mfatName": "CO2 emissions (per capita)",
      "rendering": "CHART",
      "dataflow": "DF_WBWDI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_WBWDI,/A.[TAG_GEO].EN_ATM_CO2E_PC?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=co2&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_WBWDI&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].EN_ATM_CO2E_PC&ly[cl]=TIME_PERIOD",
      "notes": "Was DF_NMDI_OTH"
    },
    {
      "id": "VII.3",
      "themeId": "VII",
      "title": "Climate-related development finance – commitment",
      "rendering": "TEXT"
    },
    {
      "id": "VII.8",
      "themeId": "VII",
      "title": "Rural population (% of total population)",
      "rendering": "CHART",
      "dataflow": "DF_POP_URBAN",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_POP_URBAN,/A.[TAG_GEO].POPRFCOU.R?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=rural%20population&pg=0&hc[Topic]=Population&hc[Urbanization]=Rural&df[ds]=ds%3ASPC2&df[id]=DF_POP_URBAN&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].POPRFCOU.R"
    },
    {
      "id": "VII.9",
      "themeId": "VII",
      "title": "Food imports (% of merchandise imports)",
      "mfatName": "Food imports (% of merchandise imports)",
      "rendering": "CHART",
      "dataflow": "DF_WBWDI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_WBWDI,/A.[TAG_GEO].TM_VAL_FOOD_ZS_UN?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=food%20imports&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_WBWDI&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].TM_VAL_FOOD_ZS_UN&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "VII.11",
      "themeId": "VII",
      "title": "Climate Finance for ODA (% total)",
      "rendering": "TEXT"
    },
    {
      "id": "VIII.1",
      "themeId": "VIII",
      "title": "Exclusive Economic Zone (EEZ) in km2",
      "rendering": "CHART",
      "dataflow": "DF_KEYFACTS",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_KEYFACTS,/A.[TAG_GEO].EEZ?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=EEZ&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_KEYFACTS&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].EEZ"
    },
    {
      "id": "VIII.5",
      "themeId": "VIII",
      "title": "-",
      "mfatName": "Percentage of population employed in fishing industry",
      "rendering": "TEXT"
    },
    {
      "id": "VIII.6",
      "themeId": "VIII",
      "title": "-",
      "mfatName": "Access fees collected (% of govt revenue)",
      "rendering": "TEXT"
    },
    {
      "id": "VIII.7",
      "themeId": "VIII",
      "title": "-",
      "mfatName": "Coastal subsistence catches (US$ millions)",
      "rendering": "TEXT"
    },
    {
      "id": "VIII.8",
      "themeId": "VIII",
      "title": "Quantity of fish, crustaceans, molluscs and other aquatic invertebrates imported (tonnes)",
      "mfatName": "Fish and Seafood Consumption",
      "rendering": "CHART",
      "dataflow": "DF_TRADE_FOOD",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_TRADE_FOOD,/A.[TAG_GEO].Q._T+AS+CK+FJ+FM+GU+KI+MH+MP+NC+NR+NU+PF+PG+PN+PW+SB+TK+TO+TV+VU+WF+WS._T.03?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&df[ds]=SPC2&df[id]=DF_TRADE_FOOD&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.Q._T%2BAS%2BCK%2BFJ%2BFM%2BGU%2BKI%2BMH%2BMP%2BNC%2BNR%2BNU%2BPF%2BPG%2BPN%2BPW%2BSB%2BTK%2BTO%2BTV%2BVU%2BWF%2BWS._T.03&ly[cl]=TIME_PERIOD&to[TIME_PERIOD]=false",
      "notes": "New 2024"
    },
    {
      "id": "VIII.9",
      "themeId": "VIII",
      "title": "Quantity of fish, crustaceans, molluscs and other aquatic invertebrates exported (tonnes)",
      "mfatName": "Fish and Seafood Consumption",
      "rendering": "CHART",
      "dataflow": "DF_TRADE_FOOD",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_TRADE_FOOD,/A.[TAG_GEO].Q._T.NR+WF+TV+TO+WS+NU+PF+CK+AS+PW+MH+KI+GU+FM+VU+SB+PG+NC+FJ.03?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&df[ds]=SPC2&df[id]=DF_TRADE_FOOD&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.Q._T.NR%2BWF%2BTV%2BTO%2BWS%2BNU%2BPF%2BCK%2BAS%2BPW%2BMH%2BKI%2BGU%2BFM%2BVU%2BSB%2BPG%2BNC%2BFJ.03&ly[cl]=TIME_PERIOD&to[TIME_PERIOD]=false",
      "notes": "New 2024"
    },
    {
      "id": "X.3",
      "themeId": "X",
      "title": "-",
      "mfatName": "Political and civil freedoms",
      "rendering": "TEXT"
    },
    {
      "id": "XI.1",
      "themeId": "XI",
      "title": "Teenage fertility rate (15-19)",
      "mfatName": "Teenage fertility rate (per 1,000 women aged 15-19 years)",
      "rendering": "CHART",
      "dataflow": "DF_VITAL",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_VITAL,/A.[TAG_GEO].TNFR._T?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?tm=teenage%20fertility&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_VITAL&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].TNFR._T&ly[cl]=TIME_PERIOD"
    },
    {
      "id": "XI.3",
      "themeId": "XI",
      "title": "Ratio of female to male labor force participation rate (%) (modeled ILO estimate)",
      "mfatName": "Ratio of female to male labour force participation rate (%) (modelled ILO estimate)",
      "rendering": "CHART",
      "dataflow": "DF_WBWDI",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_WBWDI,/A.[TAG_GEO].SL_TLF_CACT_FM_ZS?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?dq=A.[TAG_GEO].SL_TLF_CACT_FM_ZS&pd=%2C&frequency=A&lc=en&pg=0&df[ds]=ds%3ASPC2&df[id]=DF_WBWDI&df[ag]=SPC&df[vs]=1.0&ly[cl]=TIME_PERIOD&tm=wb%20"
    },
    {
      "id": "XI.7",
      "themeId": "XI",
      "title": "Labour Force Participation Rate (female)",
      "mfatName": "Labour Force Participation Rate by sex",
      "rendering": "CHART",
      "dataflow": "DF_EMPRATES",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_EMPRATES,/A.[TAG_GEO].LFPARTRATE.F._T._T._T?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?fs[0]=Topic%2C0%7CSocial%23SOC%23&pg=0&fc=Topic&df[ds]=ds%3ASPC2&df[id]=DF_EMPRATES&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].LFPARTRATE.F._T._T._T",
      "notes": "Was DF_NMDI_DEV"
    },
    {
      "id": "XI.8",
      "themeId": "XI",
      "title": "Labour Force Participation Rate (male)",
      "mfatName": "Labour Force Participation Rate by sex",
      "rendering": "CHART",
      "dataflow": "DF_EMPRATES",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_EMPRATES,/A.[TAG_GEO].LFPARTRATE.M._T._T._T?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?fs[0]=Topic%2C0%7CSocial%23SOC%23&pg=0&fc=Topic&df[ds]=ds%3ASPC2&df[id]=DF_EMPRATES&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.[TAG_GEO].LFPARTRATE.M._T._T._T",
      "notes": "Was DF_NMDI_DEV"
    },
    {
      "id": "XI.9",
      "themeId": "XI",
      "title": "-",
      "mfatName": "Status of UN Human Rights Treaties (CDC, CEDAW)",
      "rendering": "TEXT"
    },
    {
      "id": "XI.10",
      "themeId": "XI",
      "title": "-",
      "mfatName": "Human Rights Measurement Initiative - Empowerment score",
      "rendering": "TEXT"
    },
    {
      "id": "XI.11",
      "themeId": "XI",
      "title": "-",
      "mfatName": "Types of violence against women by partner",
      "rendering": "TEXT"
    },
    {
      "id": "XI.12",
      "themeId": "XI",
      "title": "-",
      "mfatName": "Human Rights Measurement Initiative  - Safety from the State score",
      "rendering": "TEXT"
    },
    {
      "id": "XI.13",
      "themeId": "XI",
      "title": "-",
      "mfatName": "National retirement scheme ratio women to men",
      "rendering": "TEXT"
    },
    {
      "id": "XI.14",
      "themeId": "XI",
      "title": "-",
      "mfatName": "Status of sexual orientation laws (parts can be core (legal) / non-core (protection against discrimination)",
      "rendering": "TEXT"
    },
    {
      "id": "XII.3",
      "themeId": "XII",
      "title": "-",
      "mfatName": "Top 5 donors",
      "rendering": "TEXT"
    },
    {
      "id": "XII.4",
      "themeId": "XII",
      "title": "-",
      "mfatName": "Total donors / fragmentation",
      "rendering": "TEXT"
    },
    {
      "id": "XII.5",
      "themeId": "XII",
      "title": "Value of transactions, aid and development finance (spent)",
      "mfatName": "Total aid flows / aid/GDP",
      "rendering": "CHART",
      "dataflow": "DF_PAM",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_PAM,/A.[TAG_GEO].VU+TV+TO+SB+WS+PG+PW+NU+NR+FM+MH+KI+FJ+CK.TRVAL._T.SPE._T?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&tm=Total%20donors&pg=0&hc[Flow%20type]=Total&hc[Donor]=Total&snb=3&df[ds]=ds%3ASPC2&df[id]=DF_PAM&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.VU%2BTV%2BTO%2BSB%2BWS%2BPG%2BPW%2BNU%2BNR%2BFM%2BMH%2BKI%2BFJ%2BCK.TRVAL._T.SPE._T&ly[cl]=TIME_PERIOD&ly[rw]=GEO_PICT&to[TIME_PERIOD]=false",
      "notes": "New 2024"
    },
    {
      "id": "XII.6",
      "themeId": "XII",
      "title": "Value of transactions, aid and development finance (committed)",
      "mfatName": "Total aid flows / aid/GDP",
      "rendering": "CHART",
      "dataflow": "DF_PAM",
      "apiUrlTemplate": "https://stats-sdmx-disseminate.pacificdata.org/rest/data/SPC,DF_PAM,/A.[TAG_GEO].VU+TV+TO+SB+WS+PG+PW+NU+NR+FM+MH+KI+FJ+CK.TRVAL._T.COM._T?dimensionAtObservation=AllDimensions",
      "visUrl": "https://stats.pacificdata.org/vis?lc=en&tm=Total%20donors&pg=0&hc[Flow%20type]=Total&hc[Donor]=Total&snb=3&df[ds]=ds%3ASPC2&df[id]=DF_PAM&df[ag]=SPC&df[vs]=1.0&pd=%2C&dq=A.VU%2BTV%2BTO%2BSB%2BWS%2BPG%2BPW%2BNU%2BNR%2BFM%2BMH%2BKI%2BFJ%2BCK.TRVAL._T.COM._T&ly[cl]=TIME_PERIOD&ly[rw]=GEO_PICT&to[TIME_PERIOD]=false",
      "notes": "New 2024"
    }
  ]
};
