// AUTO-GENERATED by scripts/import-country-snapshots.ts. Do not edit by hand.
import type { Catalogue } from "./catalogue";

export const catalogue: Catalogue = {
  generatedAt: "1970-01-01T00:00:00Z",
  sourceFile: "(not yet imported)",
  countries: [],
  themes: [],
  indicators: [],
};
